export const index = [
  {
    number: 1,
    name: "Bulbasaur",
    type: ["Grama", "Veneno"],
    description:
      "Há uma semente de planta em suas costas desde o dia em que este Pokémon nasceu. A semente cresce lentamente.",
    height: 0.7,
    weight: 6.9,
    Gender: ["masculino", "feminino"],
    category: "Semente",
    Abilities: ["Overgrow / Supercrescimento", "Chlorophyll / Clorofila"],
    baseStats: {
      hp: 45,
      attack: 49,
      defense: 49,
      spAtk: 65,
      spDef: 65,
      speed: 45,
    },
  },

  {
    number: 2,
    name: "Ivysaur ",
    type: ["Grama", "Veneno"],
    description:
      "Quando o bulbo nas costas cresce, parece perder a capacidade de ficar de pé nas patas traseiras.",
    height: 1.0,
    weight: 13.0,
    Gender: ["masculino", "feminino"],
    category: "Semente",
    Abilities: ["Overgrow / Supercrescimento", "Chlorophyll / Clorofila"],
    baseStats: {
      hp: 60,
      attack: 62,
      defense: 63,
      spAtk: 80,
      spDef: 80,
      speed: 60,
    },
  },

  {
    number: 3,
    name: "Venusaur",
    type: ["Grama", "Veneno"],
    description:
      "Sua planta floresce quando está absorvendo energia solar. Ele permanece em movimento para buscar a luz do sol.",
    height: 2.0,
    weight: 100.0,
    Gender: ["masculino", "feminino"],
    category: "Semente",
    Abilities: ["Overgrow / Supercrescimento", "Chlorophyll / Clorofila"],
    baseStats: {
      hp: 80,
      attack: 82,
      defense: 83,
      spAtk: 100,
      spDef: 100,
      speed: 80,
    },
  },
  {
    number: 4,
    name: "Charmander",
    type: ["Fogo"],
    description:
      "Tem preferência por coisas quentes. Quando chove, diz-se que o vapor jorra da ponta de sua cauda.",
    height: 0.6,
    weight: 8.5,
    Gender: ["masculino", "feminino"],
    category: "Lagarto",
    Abilities: ["Blaze / Combustão", "Solar power / Poder solar"],
    baseStats: {
      hp: 39,
      attack: 52,
      defense: 43,
      spAtk: 60,
      spDef: 50,
      speed: 65,
    },
  },
  {
    number: 5,
    name: "Charmeleon",
    type: ["Fogo"],
    description:
      "Tem uma natureza bárbara. Em batalha, ele chicoteia sua cauda de fogo e corta com suas garras afiadas.",
    height: 1.1,
    weight: 19.0,
    Gender: ["masculino", "feminino"],
    category: "Chama",
    Abilities: ["Blaze / Combustão", "Solar power / Poder solar"],
    baseStats: {
      hp: 58,
      attack: 64,
      defense: 58,
      spAtk: 80,
      spDef: 65,
      speed: 80,
    },
  },
  {
    number: 6,
    name: "Charizard",
    type: ["Fogo", "Voador"],
    description:
      "Diz-se que o fogo de Charizard queima mais quente se ele passou por duras batalhas.",
    height: 1.7,
    weight: 90.5,
    Gender: ["masculino", "feminino"],
    category: "Chama",
    Abilities: ["Blaze / Combustão", "Solar power / Poder solar"],
    baseStats: {
      hp: 78,
      attack: 84,
      defense: 78,
      spAtk: 109,
      spDef: 85,
      speed: 100,
    },
  },
  {
    number: 7,
    name: "Squirtle",
    type: ["Água"],
    description:
      "Quando retrai seu longo pescoço em sua concha, esguicha água com força vigorosa.",
    height: 0.5,
    weight: 9.0,
    Gender: ["masculino", "feminino"],
    category: "Tartaruga",
    Abilities: ["Torrent / Torrente", "Rain Dish / Regeneração de água"],
    baseStats: {
      hp: 44,
      attack: 48,
      defense: 65,
      spAtk: 50,
      spDef: 64,
      speed: 43,
    },
  },
  {
    number: 8,
    name: "Wartortle",
    type: ["Água"],
    description:
      "É reconhecido como um símbolo de longevidade. Se sua casca tiver algas, aquele Wartortle é muito velho.",
    height: 1.0,
    weight: 22.5,
    Gender: ["masculino", "feminino"],
    category: "Tartaruga",
    Abilities: ["Torrent / Torrente", "Rain Dish / Regeneração de água"],
    baseStats: {
      hp: 59,
      attack: 63,
      defense: 80,
      spAtk: 65,
      spDef: 80,
      speed: 58,
    },
  },
  {
    number: 9,
    name: "Blastoise",
    type: ["Água"],
    description:
      "Ele esmaga seu inimigo sob seu corpo pesado para causar desmaios. Em uma pitada, ele se retirará para dentro de sua casca.",
    height: 1.6,
    weight: 85.5,
    Gender: ["masculino", "feminino"],
    category: "carapaça",
    Abilities: ["Torrent / Torrente", "Rain Dish / Regeneração de água"],
    baseStats: {
      hp: 79,
      attack: 83,
      defense: 100,
      spAtk: 85,
      spDef: 105,
      speed: 78,
    },
  },
  {
    number: 10,
    name: "Caterpie",
    type: ["Inseto"],
    description:
      "Para proteção, ele libera um fedor horrível da antena em sua cabeça para afastar os inimigos.",
    height: 0.3,
    weight: 2.9,
    Gender: ["masculino", "feminino"],
    category: "verme",
    Abilities: ["Shield Dust / Escudo de poeira", "Run Away / Fugir"],
    baseStats: {
      hp: 45,
      attack: 30,
      defense: 35,
      spAtk: 20,
      spDef: 20,
      speed: 45,
    },
  },
  {
    number: 11,
    name: "Metapod",
    type: ["Inseto"],
    description:
      "Está esperando o momento de evoluir. Nesta fase, só pode endurecer, por isso permanece imóvel para evitar o ataque.",
    height: 0.7,
    weight: 9.9,
    Gender: ["masculino", "feminino"],
    category: "Casulo",
    Abilities: ["Shed Skin / Troca de pele"],
    baseStats: {
      hp: 50,
      attack: 20,
      defense: 55,
      spAtk: 25,
      spDef: 25,
      speed: 30,
    },
  },
  {
    number: 12,
    name: "Butterfree",
    type: ["Inseto", "Voador"],
    description:
      "Ele adora o néctar das flores e pode localizar canteiros de flores que tenham até pequenas quantidades de pólen.",
    height: 1.1,
    weight: 32.0,
    Gender: ["masculino", "feminino"],
    category: "Borboleta",
    Abilities: [
      "Compound Eyes / Olhos compostos",
      "Tinted Lens / Lentes coloridas ",
    ],
    baseStats: {
      hp: 60,
      attack: 45,
      defense: 50,
      spAtk: 90,
      spDef: 80,
      speed: 70,
    },
  },
  {
    number: 13,
    name: "Weedle",
    type: ["Inseto", "Veneno"],
    description:
      "Cuidado com o ferrão afiado em sua cabeça. Ele se esconde na grama e nos arbustos onde come folhas.",
    height: 0.3,
    weight: 3.2,
    Gender: ["masculino", "feminino"],
    category: "inseto peçonhento",
    Abilities: ["Shield Dust / Escudo de poeira", "Run Away / Fugir"],
    baseStats: {
      hp: 40,
      attack: 35,
      defense: 30,
      spAtk: 20,
      spDef: 20,
      speed: 50,
    },
  },
  {
    number: 14,
    name: "Kakuna",
    type: ["Inseto", "Veneno"],
    description:
      "Capaz de se mover apenas ligeiramente. Quando em perigo, pode mostrar seu ferrão e envenenar seu inimigo.",
    height: 0.6,
    weight: 10.0,
    Gender: ["masculino", "feminino"],
    category: "Casulo",
    Abilities: ["Shed Skin / Troca de pele"],
    baseStats: {
      hp: 45,
      attack: 25,
      defense: 50,
      spAtk: 25,
      spDef: 25,
      speed: 35,
    },
  },
  {
    number: 15,
    name: "Beedrill",
    type: ["Inseto", "Veneno"],
    description:
      "Tem três ferrões venenosos nas patas dianteiras e na cauda. Eles são usados para espetar seu inimigo repetidamente.",
    height: 1.0,
    weight: 29.5,
    Gender: ["masculino", "feminino"],
    category: "Abelha Venenosa",
    Abilities: ["Swarm / Enxame", "Sniper / Franco-atirador"],
    baseStats: {
      hp: 65,
      attack: 90,
      defense: 40,
      spAtk: 45,
      spDef: 80,
      speed: 75,
    },
  },
  {
    number: 16,
    name: "Pidgey",
    type: ["Normal", "Voador"],
    description:
      "Muito dócil. Se atacado, muitas vezes chuta areia para se proteger, em vez de revidar.",
    height: 0.3,
    weight: 1.8,
    Gender: ["masculino", "feminino"],
    category: "Passarinho",
    Abilities: [
      "Keen Eye / Olhar agussado",
      "Tangled Feet / Pés emaranhados",
      "Big Pecks / Bico Grande",
    ],
    baseStats: {
      hp: 40,
      attack: 45,
      defense: 40,
      spAtk: 35,
      spDef: 35,
      speed: 56,
    },
  },
  {
    number: 17,
    name: "Pidgeotto",
    type: ["Normal", "Voador"],
    description:
      "Este Pokémon está cheio de vitalidade. Ele voa constantemente em torno de seu grande território em busca de presas.",
    height: 1.1,
    weight: 30.0,
    Gender: ["masculino", "feminino"],
    category: "Passaro",
    Abilities: [
      "Keen Eye / Olhar agussado",
      "Tangled Feet / Pés emaranhados",
      "Big Pecks / Bico Grande",
    ],
    baseStats: {
      hp: 63,
      attack: 60,
      defense: 55,
      spAtk: 50,
      spDef: 50,
      speed: 71,
    },
  },
  {
    number: 18,
    name: "Pidgeot",
    type: ["Normal", "Voador"],
    description:
      "Este Pokémon voa na velocidade de Mach 2, buscando presas. Suas grandes garras são temidas como armas perversas.",
    height: 1.5,
    weight: 39.5,
    Gender: ["masculino", "feminino"],
    category: "Passaro",
    Abilities: [
      "Keen Eye / Olhar agussado",
      "Tangled Feet / Pés emaranhados",
      "Big Pecks / Bico Grande",
    ],
    baseStats: {
      hp: 83,
      attack: 80,
      defense: 75,
      spAtk: 70,
      spDef: 70,
      speed: 101,
    },
  },
  {
    number: 19,
    name: "Rattata",
    type: ["Normal"],
    description:
      "Mastigará qualquer coisa com suas presas. Se você vir um, pode ter certeza de que mais 40 vivem na área.",
    height: 0.3,
    weight: 3.5,
    Gender: ["masculino", "feminino"],
    category: "Rato",
    Abilities: ["Run Away / Fugir", "Guts / Músculos", "Hustle / Agitação"],
    baseStats: {
      hp: 30,
      attack: 56,
      defense: 35,
      spAtk: 25,
      spDef: 35,
      speed: 72,
    },
  },
  {
    number: 20,
    name: "Raticate",
    type: ["Normal"],
    description:
      "Suas patas traseiras são palmadas. Eles agem como nadadeiras, portando são capazes de nadar em rios e caçar suas presas.",
    height: 0.7,
    weight: 18.5,
    Gender: ["masculino", "feminino"],
    category: "Rato",
    Abilities: ["Run Away / Fugir", "Guts / Músculos", "Hustle / Agitação"],
    baseStats: {
      hp: 55,
      attack: 81,
      defense: 60,
      spAtk: 50,
      spDef: 70,
      speed: 97,
    },
  },
  {
    number: 21,
    name: "Spearow",
    type: ["Normal", "Voador"],
    description:
      "Inepto em voar alto. No entanto, ele pode voar muito rápido para proteger seu território.",
    height: 0.3,
    weight: 2.0,
    Gender: ["masculino", "feminino"],
    category: "Passarinho",
    Abilities: ["Keen Eye / Olhar Agussado", "Sniper / Franco-atirador"],
    baseStats: {
      hp: 40,
      attack: 60,
      defense: 30,
      spAtk: 31,
      spDef: 31,
      speed: 70,
    },
  },
  {
    number: 22,
    name: "Fearow",
    type: ["Normal", "Voador"],
    description:
      "Um Pokémon que remonta a muitos anos. Se sentir perigo, voa alto e para longe, instantaneamente.",
    height: 1.2,
    weight: 38.0,
    Gender: ["masculino", "feminino"],
    category: "Bico",
    Abilities: ["Keen Eye / Olhar Agussado", "Sniper / Franco-atirador"],
    baseStats: {
      hp: 65,
      attack: 90,
      defense: 65,
      spAtk: 61,
      spDef: 61,
      speed: 100,
    },
  },
  {
    number: 23,
    name: "Ekans",
    type: ["Veneno"],
    description:
      "Quanto mais velho fica, mais cresce. À noite, envolve seu longo corpo nos galhos das árvores para descansar.",
    height: 2.0,
    weight: 6.9,
    Gender: ["masculino", "feminino"],
    category: "Cobra",
    Abilities: [
      "Intimidate / Intimidação",
      "Shed Skin / Troca de Pele",
      "Unnerve / Tensão",
    ],
    baseStats: {
      hp: 35,
      attack: 60,
      defense: 44,
      spAtk: 40,
      spDef: 54,
      speed: 55,
    },
  },
  {
    number: 24,
    name: "Arbok",
    type: ["Veneno"],
    description:
      "Os padrões assustadores em sua barriga foram estudados. Seis variações foram confirmadas.",
    height: 3.5,
    weight: 65.0,
    Gender: ["masculino", "feminino"],
    category: "Cobra",
    Abilities: [
      "Intimidate / Intimidação",
      "Shed Skin / Troca de Pele",
      "Unnerve / Tensão",
    ],
    baseStats: {
      hp: 60,
      attack: 95,
      defense: 69,
      spAtk: 65,
      spDef: 79,
      speed: 80,
    },
  },
  {
    number: 25,
    name: "Pikachu",
    type: ["Elétrico"],
    description:
      "Quando está com raiva, descarrega imediatamente a energia armazenada nas bolsas de suas bochechas.",
    height: 0.4,
    weight: 6.0,
    Gender: ["masculino", "feminino"],
    category: "Rato",
    Abilities: ["Static / Estática", "Lightning Rod / Pára-raios"],
    baseStats: {
      hp: 35,
      attack: 55,
      defense: 40,
      spAtk: 50,
      spDef: 50,
      speed: 90,
    },
  },
  {
    number: 26,
    name: "Raichu",
    type: ["Elétrico"],
    description:
      "Sua cauda descarrega eletricidade no chão, protegendo-o de choques.",
    height: 0.8,
    weight: 30.0,
    Gender: ["masculino", "feminino"],
    category: "Rato",
    Abilities: ["Static / Estática", "Lightning Rod / Pára-raios"],
    baseStats: {
      hp: 60,
      attack: 90,
      defense: 55,
      spAtk: 90,
      spDef: 80,
      speed: 110,
    },
  },
  {
    number: 27,
    name: "Sandshrew",
    type: ["Terra"],
    description:
      "Adora banhar-se na areia de áreas secas e arenosas. Ao tomar banho de areia, o Pokémon se livra da sujeira e umidade grudadas em seu corpo.",
    height: 0.6,
    weight: 12.0,
    Gender: ["masculino", "feminino"],
    category: "Rato",
    Abilities: ["Sand Veil / Véu de Areia", "Sand Rush / Investida de Areia"],
    baseStats: {
      hp: 50,
      attack: 75,
      defense: 85,
      spAtk: 20,
      spDef: 30,
      speed: 40,
    },
  },
  {
    number: 28,
    name: "Sandslash",
    type: ["Terra"],
    description:
      "Quanto mais seca for a área em que Sandslash vive, mais duros e suaves serão os espinhos do Pokémon quando tocados.",
    height: 1.0,
    weight: 29.5,
    Gender: ["masculino", "feminino"],
    category: "Rato",
    Abilities: ["Sand Veil / Véu de Areia", "Sand Rush / Investida de Areia"],
    baseStats: {
      hp: 75,
      attack: 100,
      defense: 110,
      spAtk: 45,
      spDef: 55,
      speed: 65,
    },
  },
  {
    number: 29,
    name: "Nidoran♀",
    type: ["Veneno"],
    description:
      "As fêmeas são mais sensíveis aos cheiros do que os machos. Enquanto forrageiam, eles usam seus bigodes para verificar a direção do vento e ficar a favor dos predadores.",
    height: 0.4,
    weight: 7.0,
    Gender: ["feminino"],
    category: "Espinho Venenoso",
    Abilities: [
      "Poison Point / Ponto de Veneno",
      "Rivalry / Rivalidade",
      "Hustle / Agitação",
    ],
    baseStats: {
      hp: 55,
      attack: 47,
      defense: 52,
      spAtk: 40,
      spDef: 40,
      speed: 41,
    },
  },
  {
    number: 30,
    name: "Nidorina",
    type: ["Veneno"],
    description:
      "O chifre em sua cabeça está atrofiado. Acredita-se que isso aconteça para que os filhos de Nidorina não sejam cutucados enquanto a mãe os alimenta.",
    height: 0.8,
    weight: 20.0,
    Gender: ["feminino"],
    category: "Espinho Venenoso",
    Abilities: [
      "Poison Point / Ponto de Veneno",
      "Rivalry / Rivalidade",
      "Hustle / Agitação",
    ],
    baseStats: {
      hp: 70,
      attack: 62,
      defense: 67,
      spAtk: 55,
      spDef: 55,
      speed: 56,
    },
  },
  {
    number: 31,
    name: "Nidoqueen",
    type: ["Veneno", "Terra"],
    description:
      "Nidoqueen é melhor na defesa do que no ataque. Com escamas como armaduras, este Pokémon protegerá seus filhos de qualquer tipo de ataque.",
    height: 1.3,
    weight: 60.0,
    Gender: ["feminino"],
    category: "Broca",
    Abilities: [
      "Poison Point / Ponto de Veneno",
      "Rivalry / Rivalidade",
      "Sheer Force / Força Bruta",
    ],
    baseStats: {
      hp: 90,
      attack: 92,
      defense: 87,
      spAtk: 75,
      spDef: 85,
      speed: 76,
    },
  },
  {
    number: 32,
    name: "Nidoran♂",
    type: ["Veneno"],
    description:
      "O chifre na testa de um Nidoran masculino contém um poderoso veneno. Este é um Pokémon muito cauteloso, sempre esticando suas grandes orelhas.",
    height: 0.5,
    weight: 9.0,
    Gender: ["masculino"],
    category: "Espinho Venenoso",
    Abilities: [
      "Poison Point / Ponto de Veneno",
      "Rivalry / Rivalidade",
      "Hustle / Agitação",
    ],
    baseStats: {
      hp: 46,
      attack: 57,
      defense: 40,
      spAtk: 40,
      spDef: 40,
      speed: 50,
    },
  },
  {
    number: 33,
    name: "Nidorino",
    type: ["Veneno"],
    description:
      "Com um chifre mais duro que diamante, este Pokémon anda por aí quebrando pedregulhos enquanto procura uma pedra da lua.",
    height: 0.9,
    weight: 19.5,
    Gender: ["masculino"],
    category: "Espinho Venenoso",
    Abilities: [
      "Poison Point / Ponto de Veneno",
      "Rivalry / Rivalidade",
      "Hustle / Agitação",
    ],
    baseStats: {
      hp: 61,
      attack: 72,
      defense: 57,
      spAtk: 55,
      spDef: 55,
      speed: 65,
    },
  },
  {
    number: 34,
    name: "Nidoking",
    type: ["Veneno", "Terra"],
    description:
      "Quando fica furioso, é impossível controlar. Mas na presença de uma Nidoqueen com quem convive há muito tempo, Nidoking se acalma.",
    height: 1.4,
    weight: 62.0,
    Gender: ["masculino"],
    category: "Broca",
    Abilities: [
      "Poison Point / Ponto de Veneno",
      "Rivalry / Rivalidade",
      "Sheer Force / Força Bruta",
    ],
    baseStats: {
      hp: 81,
      attack: 102,
      defense: 77,
      spAtk: 85,
      spDef: 75,
      speed: 85,
    },
  },
  {
    number: 35,
    name: "Clefairy",
    type: ["Fada"],
    description:
      "Dizem que a felicidade virá para aqueles que virem uma reunião de Clefairy dançando sob a lua cheia.",
    height: 0.6,
    weight: 7.5,
    Gender: ["feminino", "masculino"],
    category: "Fada",
    Abilities: [
      "Cute Charm / Encanto Adorável",
      "Magic Guard / Guarda Mágica",
      "Friend Guard / Guarda Amiga",
    ],
    baseStats: {
      hp: 70,
      attack: 45,
      defense: 48,
      spAtk: 60,
      spDef: 65,
      speed: 35,
    },
  },
  {
    number: 36,
    name: "Clefable",
    type: ["Fada"],
    description:
      "Um tímido Pokémon fada que raramente é visto, ele corre e se esconde no momento em que detecta as pessoas.",
    height: 1.3,
    weight: 40.0,
    Gender: ["feminino", "masculino"],
    category: "Fada",
    Abilities: [
      "Cute Charm / Encanto Adorável",
      "Magic Guard / Guarda Mágica",
      "Unaware / Inconsciente",
    ],
    baseStats: {
      hp: 95,
      attack: 70,
      defense: 73,
      spAtk: 95,
      spDef: 90,
      speed: 60,
    },
  },
  {
    number: 37,
    name: "Vulpix",
    type: ["Fogo"],
    description:
      "Enquanto jovem, ele tem seis lindas caudas. Quando cresce, várias novas caudas brotam.",
    height: 0.6,
    weight: 9.9,
    Gender: ["feminino", "masculino"],
    category: "Raposa",
    Abilities: ["Flash Fire / Absorve Fogo", "Drought / Seca"],
    baseStats: {
      hp: 38,
      attack: 41,
      defense: 40,
      spAtk: 50,
      spDef: 65,
      speed: 65,
    },
  },
  {
    number: 38,
    name: "Ninetales",
    type: ["Fogo"],
    description:
      "Diz-se que vive 1.000 anos e cada uma de suas caudas é carregada de poderes sobrenaturais.",
    height: 1.1,
    weight: 19.9,
    Gender: ["feminino", "masculino"],
    category: "Raposa",
    Abilities: ["Flash Fire / Absorve Fogo", "Drought / Seca"],
    baseStats: {
      hp: 73,
      attack: 76,
      defense: 75,
      spAtk: 81,
      spDef: 100,
      speed: 100,
    },
  },
  {
    number: 39,
    name: "Jigglypuff",
    type: ["Normal", "Fada"],
    description:
      "Quando seus olhos enormes vacilam, ele canta uma melodia misteriosamente reconfortante que embala seus inimigos para dormir.",
    height: 0.5,
    weight: 5.5,
    Gender: ["feminino", "masculino"],
    category: "Balão",
    Abilities: [
      "Cute Charm / Encanto Adorável",
      "Competitive / Competitiva",
      "Friend Guard / Guarda Amiga",
    ],
    baseStats: {
      hp: 115,
      attack: 45,
      defense: 20,
      spAtk: 45,
      spDef: 25,
      speed: 20,
    },
  },
  {
    number: 40,
    name: "Wigglytuff",
    type: ["Normal", "Fada"],
    description:
      "Tem uma pelagem muito fina. Tome cuidado para não irritá-lo, ou ele pode inflar constantemente e bater com força.",
    height: 1.0,
    weight: 12.0,
    Gender: ["feminino", "masculino"],
    category: "Balão",
    Abilities: [
      "Cute Charm / Encanto Adorável",
      "Competitive / Competitiva",
      "Fisk / Fiscalizar",
    ],
    baseStats: {
      hp: 140,
      attack: 70,
      defense: 45,
      spAtk: 85,
      spDef: 50,
      speed: 45,
    },
  },
  {
    number: 41,
    name: "Zubat",
    type: ["Veneno", "Voador"],
    description:
      "Ele emite ondas ultrassônicas de sua boca para verificar seus arredores. Mesmo em cavernas apertadas, Zubat voa com habilidade.",
    height: 0.8,
    weight: 7.5,
    Gender: ["feminino", "masculino"],
    category: "Morcego",
    Abilities: ["Inner Focus / Foco Interno", "Infiltrator / Infiltrador"],
    baseStats: {
      hp: 40,
      attack: 45,
      defense: 35,
      spAtk: 30,
      spDef: 40,
      speed: 55,
    },
  },
  {
    number: 42,
    name: "Golbat",
    type: ["Veneno", "Voador"],
    description:
      "Adora beber o sangue de outras criaturas. Diz-se que, se encontrar outros de sua espécie passando fome, às vezes compartilha o sangue que colheu.",
    height: 1.6,
    weight: 55.0,
    Gender: ["feminino", "masculino"],
    category: "Morcego",
    Abilities: ["Inner Focus / Foco Interno", "Infiltrator / Infiltrador"],
    baseStats: {
      hp: 75,
      attack: 80,
      defense: 70,
      spAtk: 65,
      spDef: 75,
      speed: 90,
    },
  },
  {
    number: 43,
    name: "Oddish",
    type: ["Grama", "Veneno"],
    description:
      "Se exposto ao luar, ele começa a se mover. Ele vagueia por toda parte à noite para espalhar suas sementes.",
    height: 0.5,
    weight: 5.4,
    Gender: ["feminino", "masculino"],
    category: "Erva",
    Abilities: ["Chlorophyll / Clorofila", "Run Away / Fugir"],
    baseStats: {
      hp: 45,
      attack: 50,
      defense: 55,
      spAtk: 75,
      spDef: 65,
      speed: 30,
    },
  },
  {
    number: 44,
    name: "Gloom",
    type: ["Grama", "Veneno"],
    description:
      "Seus pistilos exalam um odor incrivelmente fétido. O fedor horrível pode causar desmaios a uma distância de 1,25 milhas.",
    height: 0.8,
    weight: 8.6,
    Gender: ["feminino", "masculino"],
    category: "Erva",
    Abilities: ["Chlorophyll / Clorofila", "Stench / Fedor"],
    baseStats: {
      hp: 60,
      attack: 65,
      defense: 70,
      spAtk: 85,
      spDef: 75,
      speed: 40,
    },
  },
  {
    number: 45,
    name: "Vileplume",
    type: ["Grama", "Veneno"],
    description:
      "Tem as maiores pétalas do mundo. A cada passo, as pétalas sacodem pesadas nuvens de pólen tóxico.",
    height: 1.2,
    weight: 18.6,
    Gender: ["feminino", "masculino"],
    category: "Flor",
    Abilities: ["Chlorophyll / Clorofila", "Effect Spore / Efeito Esporo"],
    baseStats: {
      hp: 75,
      attack: 80,
      defense: 85,
      spAtk: 110,
      spDef: 90,
      speed: 50,
    },
  },
  {
    number: 46,
    name: "Paras",
    type: ["Inseto", "Grama"],
    description:
      "Constroi tocas sob o solo para roer as raízes das árvores. Os cogumelos nas costas absorvem a maior parte da nutrição.",
    height: 0.3,
    weight: 5.4,
    Gender: ["feminino", "masculino"],
    category: "Cogumelo",
    Abilities: [
      "Effect Spore / Efeito Espora",
      "Dry Skin / Pele Seca",
      "Damp / umidade",
    ],
    baseStats: {
      hp: 35,
      attack: 70,
      defense: 55,
      spAtk: 45,
      spDef: 55,
      speed: 25,
    },
  },
  {
    number: 47,
    name: "Parasect",
    type: ["Inseto", "Grama"],
    description:
      "O inseto hospedeiro tem sua energia drenada pelo cogumelo em suas costas. O cogumelo parece fazer todo o pensamento.",
    height: 1.0,
    weight: 29.5,
    Gender: ["feminino", "masculino"],
    category: "Cogumelo",
    Abilities: [
      "Effect Spore / Efeito Espora",
      "Dry Skin / Pele Seca",
      "Damp / umidade",
    ],
    baseStats: {
      hp: 60,
      attack: 95,
      defense: 80,
      spAtk: 60,
      spDef: 80,
      speed: 30,
    },
  },
  {
    number: 48,
    name: "Venonat",
    type: ["Inseto", "Veneno"],
    description:
      "Veneno escorre de todo o seu corpo. Ele pega pequenos Pokémon insetos à noite que são atraídos pela luz.",
    height: 1.0,
    weight: 30.0,
    Gender: ["feminino", "masculino"],
    category: "Inseto",
    Abilities: [
      "Compound Eyes / Olhos Compostos",
      "Tinted Lens / Lentes Coloridas",
      "Run Away / Fugir",
    ],
    baseStats: {
      hp: 60,
      attack: 55,
      defense: 50,
      spAtk: 40,
      spDef: 55,
      speed: 45,
    },
  },
  {
    number: 49,
    name: "Venomoth",
    type: ["Inseto", "Veneno"],
    description:
      "As asas são cobertas com escamas semelhantes a poeira. Cada vez que bate as asas, solta poeira altamente tóxica.",
    height: 1.5,
    weight: 12.5,
    Gender: ["feminino", "masculino"],
    category: "Inseto",
    Abilities: [
      "Shield Dust / Pó Escudo",
      "Tinted Lens / Lente Colorida",
      "Wonder Skin / Pele Maravilhosa",
    ],
    baseStats: {
      hp: 70,
      attack: 65,
      defense: 60,
      spAtk: 90,
      spDef: 75,
      speed: 90,
    },
  },
  {
    number: 50,
    name: "Diglett",
    type: ["Terra"],
    description:
      "Ele vive a cerca de um metro no subsolo, onde se alimenta de raízes de plantas. Às vezes aparece acima do solo.",
    height: 0.2,
    weight: 0.8,
    Gender: ["feminino", "masculino"],
    category: "Toupeira",
    Abilities: [
      "Sand Veil / Véu de Areia",
      "Arena Trap / Armadilha de Areia",
      "Sand Force / Força de Areia",
    ],
    baseStats: {
      hp: 10,
      attack: 55,
      defense: 25,
      spAtk: 35,
      spDef: 45,
      speed: 95,
    },
  },
  {
    number: 51,
    name: "Dugtrio",
    type: ["Terra"],
    description:
      "Suas três cabeças balançam separadamente para cima e para baixo para soltar o solo próximo, facilitando a escavação.",
    height: 0.7,
    weight: 33.3,
    Gender: ["feminino", "masculino"],
    category: "Toupeira",
    Abilities: [
      "Sand Veil / Véu de Areia",
      "Arena Trap / Armadilha de Areia",
      "Sand Force / Força de Areia",
    ],
    baseStats: {
      hp: 35,
      attack: 100,
      defense: 50,
      spAtk: 50,
      spDef: 70,
      speed: 120,
    },
  },
  {
    number: 52,
    name: "Meowth",
    type: ["Normal"],
    description:
      "Tudo o que faz é dormir durante o dia. À noite, patrulha seu território com os olhos brilhando.",
    height: 0.4,
    weight: 4.2,
    Gender: ["feminino", "masculino"],
    category: "Gato arranhador",
    Abilities: [
      "Pickup / Apanhar",
      "Technician / Perito",
      "Unnerve / Nervosismo",
    ],
    baseStats: {
      hp: 40,
      attack: 45,
      defense: 35,
      spAtk: 40,
      spDef: 40,
      speed: 90,
    },
  },
  {
    number: 53,
    name: "Persian",
    type: ["Normal"],
    description:
      "Embora seu pelo tenha muitos admiradores, é difícil criá-lo como animal de estimação por causa de sua mesquinhez inconstante.",
    height: 1.0,
    weight: 32.0,
    Gender: ["feminino", "masculino"],
    category: "Gato de classe",
    Abilities: [
      "Limber / Flexibilidade",
      "Technician / Perito",
      "Unnerve / Nervosismo",
    ],
    baseStats: {
      hp: 65,
      attack: 70,
      defense: 60,
      spAtk: 65,
      spDef: 65,
      speed: 115,
    },
  },
  {
    number: 54,
    name: "Psyduck",
    type: ["Água"],
    description:
      "É constantemente assolado por uma dor de cabeça. Quando a dor de cabeça fica intensa, ela começa a usar poderes misteriosos.",
    height: 0.8,
    weight: 19.6,
    Gender: ["feminino", "masculino"],
    category: "Pato",
    Abilities: [
      "Damp / Umidade",
      "Cloud Nine / Névoa Espessa",
      "Swift Swim / Nado Rápido",
    ],
    baseStats: {
      hp: 50,
      attack: 52,
      defense: 48,
      spAtk: 65,
      spDef: 50,
      speed: 55,
    },
  },
  {
    number: 55,
    name: "Golduck",
    type: ["Água"],
    description:
      "Quando nada a toda velocidade usando seus longos membros palmados, a joia em sua testa de alguma forma começa a brilhar.",
    height: 1.7,
    weight: 76.6,
    Gender: ["feminino", "masculino"],
    category: "Pato",
    Abilities: [
      "Damp / Umidade",
      "Cloud Nine / Névoa Espessa",
      "Swift Swim / Nado Rápido",
    ],
    baseStats: {
      hp: 80,
      attack: 82,
      defense: 78,
      spAtk: 95,
      spDef: 80,
      speed: 85,
    },
  },
  {
    number: 56,
    name: "Mankey",
    type: ["Lutador"],
    description:
      "Vive em grupos nas copas das árvores. Quando se perde de vista seu grupo, fica furioso com sua solidão.",
    height: 0.5,
    weight: 28.0,
    Gender: ["feminino", "masculino"],
    category: "Primata suino",
    Abilities: [
      "Vital Spirit / Espírito Vital",
      "Anger Point / Raiva",
      "Defiant / Desafio",
    ],
    baseStats: {
      hp: 40,
      attack: 80,
      defense: 35,
      spAtk: 35,
      spDef: 45,
      speed: 70,
    },
  },
  {
    number: 57,
    name: "Primeape",
    type: ["Lutador"],
    description:
      "Ele fica extremamente furioso se sentir que alguém está olhando para ele. Ele persegue qualquer um que tente ofuscar seu brilho.",
    height: 1.0,
    weight: 32.0,
    Gender: ["feminino", "masculino"],
    category: "Primata suino",
    Abilities: [
      "Vital Spirit / Espírito Vital",
      "Anger Point / Raiva",
      "Defiant / Desafio",
    ],
    baseStats: {
      hp: 65,
      attack: 105,
      defense: 60,
      spAtk: 60,
      spDef: 70,
      speed: 95,
    },
  },
  {
    number: 58,
    name: "Growlithe",
    type: ["Fogo"],
    description:
      "Tem uma natureza corajosa e confiável. Ele enfrenta destemidamente inimigos maiores e mais fortes.",
    height: 0.7,
    weight: 19.0,
    Gender: ["feminino", "masculino"],
    category: "Cachorrinho",
    Abilities: [
      "Intimidate / Intimidação",
      "Flash Fire / Absorve Fogo",
      "Justified / Justificado",
    ],
    baseStats: {
      hp: 55,
      attack: 70,
      defense: 45,
      spAtk: 70,
      spDef: 50,
      speed: 60,
    },
  },
  {
    number: 59,
    name: "Arcanine",
    type: ["Fogo"],
    description:
      "Um pergaminho antigo mostra que as pessoas foram cativadas por seu movimento enquanto corria pelas pradarias.",
    height: 1.9,
    weight: 155.0,
    Gender: ["feminino", "masculino"],
    category: "Lendário",
    Abilities: [
      "Intimidate / Intimidação",
      "Flash Fire / Absorve Fogo",
      "Justified / Justificado",
    ],
    baseStats: {
      hp: 90,
      attack: 110,
      defense: 80,
      spAtk: 100,
      spDef: 80,
      speed: 95,
    },
  },
  {
    number: 60,
    name: "Poliwag",
    type: ["Água"],
    description:
      "Para Poliwag, nadar é mais fácil do que caminhar. O padrão de redemoinho em sua barriga é, na verdade, parte das entranhas do Pokémon que aparecem através da pele.",
    height: 0.6,
    weight: 12.4,
    Gender: ["feminino", "masculino"],
    category: "Girino",
    Abilities: [
      "Water Absorb / Absorver Água",
      "Damp / Umidade",
      "Swift Swim / Nado Rápido",
    ],
    baseStats: {
      hp: 40,
      attack: 50,
      defense: 40,
      spAtk: 40,
      spDef: 40,
      speed: 90,
    },
  },
  {
    number: 61,
    name: "Poliwhirl",
    type: ["Água"],
    description:
      "Olhar para o redemoinho em sua barriga causa sonolência. Essa característica de Poliwhirl tem sido usada no lugar de canções de ninar para fazer as crianças dormirem.",
    height: 1.0,
    weight: 20.0,
    Gender: ["feminino", "masculino"],
    category: "Girino",
    Abilities: [
      "Water Absorb / Absorver Água",
      "Damp / Umidade",
      "Swift Swim / Nado Rápido",
    ],
    baseStats: {
      hp: 65,
      attack: 65,
      defense: 65,
      spAtk: 50,
      spDef: 50,
      speed: 90,
    },
  },
  {
    number: 62,
    name: "Poliwrath",
    type: ["Água", "Lutador"],
    description:
      "Seu corpo é músculo sólido. Ao nadar em mares frios, Poliwrath usa seus braços impressionantes para quebrar o gelo flutuante e seguir em frente.",
    height: 1.3,
    weight: 54.0,
    Gender: ["feminino", "masculino"],
    category: "Sapo",
    Abilities: [
      "Water Absorb / Absorver Água",
      "Damp / Umidade",
      "Swift Swim / Nado Rápido",
    ],
    baseStats: {
      hp: 90,
      attack: 95,
      defense: 95,
      spAtk: 70,
      spDef: 90,
      speed: 70,
    },
  },
  {
    number: 63,
    name: "Abra",
    type: ["Psíquico"],
    description:
      "Este Pokémon usa seus poderes psíquicos enquanto dorme. O conteúdo dos sonhos de Abra afeta os poderes que o Pokémon possui.",
    height: 0.9,
    weight: 19.5,
    Gender: ["feminino", "masculino"],
    category: "Psíquico",
    Abilities: [
      "Synchronize / Sincronismo",
      "Inner Focus / Foco Interno",
      "Magic Guard / Guarda Mágica",
    ],
    baseStats: {
      hp: 25,
      attack: 20,
      defense: 15,
      spAtk: 105,
      spDef: 55,
      speed: 90,
    },
  },
  {
    number: 64,
    name: "Kadabra",
    type: ["Psíquico"],
    description:
      "Usando seu poder psíquico, Kadabra levita enquanto dorme. Ele usa sua cauda elástica como travesseiro.",
    height: 1.3,
    weight: 56.5,
    Gender: ["feminino", "masculino"],
    category: "Psíquico",
    Abilities: [
      "Synchronize / Sincronismo",
      "Inner Focus / Foco Interno",
      "Magic Guard / Guarda Mágica",
    ],
    baseStats: {
      hp: 40,
      attack: 35,
      defense: 30,
      spAtk: 120,
      spDef: 70,
      speed: 105,
    },
  },
  {
    number: 65,
    name: "Alakazam",
    type: ["Psíquico"],
    description:
      "Tem um nível incrivelmente alto de inteligência. Alguns dizem que Alakazam se lembra de tudo o que acontece com ele, desde o nascimento até a morte.",
    height: 1.5,
    weight: 48.0,
    Gender: ["feminino", "masculino"],
    category: "Psíquico",
    Abilities: [
      "Synchronize / Sincronismo",
      "Inner Focus / Foco Interno",
      "Magic Guard / Guarda Mágica",
    ],
    baseStats: {
      hp: 55,
      attack: 50,
      defense: 45,
      spAtk: 135,
      spDef: 95,
      speed: 120,
    },
  },
  {
    number: 66,
    name: "Machop",
    type: ["Lutador"],
    description:
      "Todo o seu corpo é composto por músculos. Mesmo sendo do tamanho de uma criança humana, pode arremessar 100 adultos.",
    height: 0.8,
    weight: 19.5,
    Gender: ["feminino", "masculino"],
    category: "Superpoderoso",
    Abilities: [
      "Guts / Determinação",
      "No Guard / Sem-Erro",
      "Steadfast / Firmeza",
    ],
    baseStats: {
      hp: 70,
      attack: 80,
      defense: 50,
      spAtk: 35,
      spDef: 35,
      speed: 35,
    },
  },
  {
    number: 67,
    name: "Machoke",
    type: ["Lutador"],
    description:
      "Seu corpo musculoso é tão poderoso que deve usar um cinto de economia de energia para poder regular seus movimentos.",
    height: 1.5,
    weight: 70.5,
    Gender: ["feminino", "masculino"],
    category: "Superpoderoso",
    Abilities: [
      "Guts / Determinação",
      "No Guard / Sem-Erro",
      "Steadfast / Firmeza",
    ],
    baseStats: {
      hp: 80,
      attack: 100,
      defense: 70,
      spAtk: 50,
      spDef: 60,
      speed: 45,
    },
  },
  {
    number: 68,
    name: "Machamp",
    type: ["Lutador"],
    description:
      "Ele soca com seus quatro braços em uma velocidade estonteante. Ele pode lançar 1.000 socos em dois segundos.",
    height: 1.6,
    weight: 130.0,
    Gender: ["feminino", "masculino"],
    category: "Superpoderoso",
    Abilities: [
      "Guts / Determinação",
      "No Guard / Sem-Erro",
      "Steadfast / Firmeza",
    ],
    baseStats: {
      hp: 90,
      attack: 130,
      defense: 80,
      spAtk: 65,
      spDef: 85,
      speed: 55,
    },
  },
  {
    number: 69,
    name: "Bellsprout",
    type: ["Grama", "Veneno"],
    description:
      "Prefere lugares quentes e úmidos. Ele captura pequenos insetos com suas vinhas e os devora.",
    height: 0.7,
    weight: 4.0,
    Gender: ["feminino", "masculino"],
    category: "Flor",
    Abilities: ["Chlorophyll / Clorofila", "Gluttony / Gula"],
    baseStats: {
      hp: 50,
      attack: 75,
      defense: 35,
      spAtk: 70,
      spDef: 30,
      speed: 40,
    },
  },
  {
    number: 70,
    name: "Weepinbell",
    type: ["Grama", "Veneno"],
    description:
      "Quando está com fome, engole tudo o que se mexe. Sua presa infeliz é dissolvida por ácidos fortes.",
    height: 1.0,
    weight: 6.4,
    Gender: ["feminino", "masculino"],
    category: "Planta Carnívora",
    Abilities: ["Chlorophyll / Clorofila", "Gluttony / Gula"],
    baseStats: {
      hp: 65,
      attack: 90,
      defense: 50,
      spAtk: 85,
      spDef: 45,
      speed: 55,
    },
  },
  {
    number: 71,
    name: "Victreebel",
    type: ["Grama", "Veneno"],
    description:
      "Atrai a presa com o doce aroma do mel. Engolida inteira, a presa é dissolvida em um dia, com ossos e tudo.",
    height: 1.7,
    weight: 15.5,
    Gender: ["feminino", "masculino"],
    category: "Planta Carnívora",
    Abilities: ["Chlorophyll / Clorofila", "Gluttony / Gula"],
    baseStats: {
      hp: 80,
      attack: 105,
      defense: 65,
      spAtk: 100,
      spDef: 70,
      speed: 70,
    },
  },
  {
    number: 72,
    name: "Tentacool",
    type: ["Água", "Veneno"],
    description:
      "Tentacool não é um nadador particularmente forte. Ele flutua pela superfície de mares rasos enquanto procura por presas.",
    height: 0.9,
    weight: 45.5,
    Gender: ["feminino", "masculino"],
    category: "Medusa",
    Abilities: [
      "Clear Body / Corpo Clara",
      "Liquid Ooze / Lodo Líquido",
      "Rain Dish / Cura Chuvosa",
    ],
    baseStats: {
      hp: 40,
      attack: 40,
      defense: 35,
      spAtk: 50,
      spDef: 100,
      speed: 70,
    },
  },
  {
    number: 73,
    name: "Tentacruel",
    type: ["Água", "Veneno"],
    description:
      "Quando as esferas vermelhas na cabeça de Tentacruel brilharem intensamente, cuidado. O Pokémon está prestes a disparar uma explosão de ondas ultrassônicas.",
    height: 1.6,
    weight: 55.0,
    Gender: ["feminino", "masculino"],
    category: "Medusa",
    Abilities: [
      "Clear Body / Corpo Clara",
      "Liquid Ooze / Lodo Líquido",
      "Rain Dish / Cura Chuvosa",
    ],
    baseStats: {
      hp: 80,
      attack: 70,
      defense: 65,
      spAtk: 80,
      spDef: 120,
      speed: 100,
    },
  },
  {
    number: 74,
    name: "Geodude",
    type: ["Pedra", "Terra"],
    description:
      "Comumente encontrado perto de trilhas de montanha e similares. Se você pisar em um por acidente, ele fica com raiva.",
    height: 0.4,
    weight: 20.0,
    Gender: ["feminino", "masculino"],
    category: "Pedregulho",
    Abilities: [
      "Rock Head / Cabeça de Pedra",
      "Sturdy / Firme",
      "Sand Veil / Véu de Areia",
    ],
    baseStats: {
      hp: 40,
      attack: 80,
      defense: 100,
      spAtk: 30,
      spDef: 30,
      speed: 20,
    },
  },
  {
    number: 75,
    name: "Graveler",
    type: ["Pedra", "Terra"],
    description:
      "Frequentemente visto rolando por trilhas nas montanhas. Obstáculos são apenas coisas para rolar, não evitar.",
    height: 1.0,
    weight: 105.0,
    Gender: ["feminino", "masculino"],
    category: "Pedregulho",
    Abilities: [
      "Rock Head / Cabeça de Pedra",
      "Sturdy / Firme",
      "Sand Veil / Véu de Areia",
    ],
    baseStats: {
      hp: 55,
      attack: 95,
      defense: 115,
      spAtk: 45,
      spDef: 45,
      speed: 35,
    },
  },
  {
    number: 76,
    name: "Golem",
    type: ["Pedra", "Terra"],
    description:
      "Depois de trocar de pele, seu corpo fica macio e esbranquiçado. Sua pele endurece quando exposta ao ar.",
    height: 1.4,
    weight: 300.0,
    Gender: ["feminino", "masculino"],
    category: "Megatonelada",
    Abilities: [
      "Rock Head / Cabeça de Pedra",
      "Sturdy / Firme",
      "Sand Veil / Véu de Areia",
    ],
    baseStats: {
      hp: 80,
      attack: 120,
      defense: 130,
      spAtk: 55,
      spDef: 65,
      speed: 45,
    },
  },
  {
    number: 77,
    name: "Ponyta",
    type: ["Fogo"],
    description:
      "Cerca de uma hora após o nascimento, a crina e a cauda ardentes de Ponyta crescem, dando ao Pokémon uma aparência impressionante.",
    height: 1.0,
    weight: 30.0,
    Gender: ["feminino", "masculino"],
    category: "Cavalo de Fogo",
    Abilities: [
      "Run Away / Fugir",
      "Flash Fire / Absorve Fogo",
      "Flame Body / Corpo de Fogo",
    ],
    baseStats: {
      hp: 50,
      attack: 85,
      defense: 55,
      spAtk: 65,
      spDef: 65,
      speed: 90,
    },
  },
  {
    number: 78,
    name: "Rapidash",
    type: ["Fogo"],
    description:
      "Ele galopa a quase 150 mph. Com sua crina ardendo ferozmente, ele corre como se fosse uma flecha.",
    height: 1.7,
    weight: 95.0,
    Gender: ["feminino", "masculino"],
    category: "Cavalo de Fogo",
    Abilities: [
      "Run Away / Fugir",
      "Flash Fire / Absorve Fogo",
      "Flame Body / Corpo de Fogo",
    ],
    baseStats: {
      hp: 65,
      attack: 100,
      defense: 70,
      spAtk: 80,
      spDef: 80,
      speed: 105,
    },
  },
  {
    number: 79,
    name: "Slowpoke",
    type: ["Água", "Psíquico"],
    description:
      "É incrivelmente lento e idiota. Leva cinco segundos para sentir dor quando está sob ataque.",
    height: 1.2,
    weight: 36.0,
    Gender: ["feminino", "masculino"],
    category: "Caracol",
    Abilities: [
      "Oblivious / Desatento",
      "Own Tempo / Ritmo Próprio",
      "Regenerator / Regeneração",
    ],
    baseStats: {
      hp: 90,
      attack: 65,
      defense: 65,
      spAtk: 40,
      spDef: 40,
      speed: 15,
    },
  },
  {
    number: 80,
    name: "Slowbro",
    type: ["Água", "Psíquico"],
    description:
      "Quando um Slowpoke foi caçar no mar, seu rabo foi mordido por um Shellder. Isso o fez evoluir para Slowbro.",
    height: 1.6,
    weight: 78.5,
    Gender: ["feminino", "masculino"],
    category: "Caracol",
    Abilities: [
      "Oblivious / Desatento",
      "Own Tempo / Ritmo Próprio",
      "Regenerator / Regeneração",
    ],
    baseStats: {
      hp: 95,
      attack: 75,
      defense: 110,
      spAtk: 100,
      spDef: 80,
      speed: 30,
    },
  },
  {
    number: 81,
    name: "Magnemite",
    type: ["Elétrico", "Aço"],
    description:
      "As ondas eletromagnéticas emitidas pelas unidades nas laterais de sua cabeça expulsam a antigravidade, o que permite que ela flutue.",
    height: 0.3,
    weight: 6.0,
    Gender: ["sem gênero"],
    category: "Magnético",
    Abilities: ["Magnet Pull / Ímã", "Sturdy / Firme", "Analytic / Analítico"],
    baseStats: {
      hp: 25,
      attack: 35,
      defense: 70,
      spAtk: 95,
      spDef: 55,
      speed: 45,
    },
  },
  {
    number: 82,
    name: "Magneton",
    type: ["Elétrico", "Aço"],
    description:
      "Três Magnemite estão ligados por uma forte força magnética. Dores de ouvido ocorrerão se você chegar muito perto.",
    height: 1.0,
    weight: 60.0,
    Gender: ["sem gênero"],
    category: "Magnético",
    Abilities: ["Magnet Pull / Ímã", "Sturdy / Firme", "Analytic / Analítico"],
    baseStats: {
      hp: 50,
      attack: 60,
      defense: 95,
      spAtk: 120,
      spDef: 70,
      speed: 70,
    },
  },
  {
    number: 83,
    name: "Farfetch'd",
    type: ["Normal", "Voador"],
    description:
      "Não pode viver sem o caule que segura. É por isso que defende o caule dos atacantes com sua vida.",
    height: 0.8,
    weight: 15.0,
    Gender: ["feminino", "masculino"],
    category: "Pato Selvagem",
    Abilities: [
      "Keen Eye / Olho Vivo",
      "Inner Focus / Foco Interno",
      "Defiant / Intrépido",
    ],
    baseStats: {
      hp: 52,
      attack: 90,
      defense: 55,
      spAtk: 58,
      spDef: 62,
      speed: 60,
    },
  },
  {
    number: 84,
    name: "Doduo",
    type: ["Normal", "Voador"],
    description:
      "Suas asas curtas dificultam o vôo. Em vez disso, este Pokémon corre em alta velocidade com pernas desenvolvidas.",
    height: 1.4,
    weight: 39.2,
    Gender: ["feminino", "masculino"],
    category: "Ave de Duas Cabeças",
    Abilities: [
      "Run Away / Fugir",
      "Early Bird / Passarinho Madrugador",
      "Tangled Feet / Pés emaranhados",
    ],
    baseStats: {
      hp: 35,
      attack: 85,
      defense: 45,
      spAtk: 35,
      spDef: 35,
      speed: 75,
    },
  },
  {
    number: 85,
    name: "Dodrio",
    type: ["Normal", "Voador"],
    description:
      "Uma das duas cabeças de Doduo se divide para formar uma espécie única. Ele corre perto de 40 mph em pradarias.",
    height: 1.8,
    weight: 85.2,
    Gender: ["feminino", "masculino"],
    category: "Ave de Três Cabeças",
    Abilities: [
      "Run Away / Fugir",
      "Early Bird / Passarinho Madrugador",
      "Tangled Feet / Pés emaranhados",
    ],
    baseStats: {
      hp: 60,
      attack: 110,
      defense: 70,
      spAtk: 60,
      spDef: 60,
      speed: 110,
    },
  },
  {
    number: 86,
    name: "Seel",
    type: ["Água"],
    description:
      "Adora condições de frio congelante. Gosta de nadar em um clima gelado de cerca de 14 graus Fahrenheit.",
    height: 1.1,
    weight: 90.0,
    Gender: ["feminino", "masculino"],
    category: "Leão Marinho",
    Abilities: [
      "Thick Fat / Gordura Espessa",
      "Hydration / Hidratação",
      "Ice Body / Corpo de Gelo",
    ],
    baseStats: {
      hp: 65,
      attack: 45,
      defense: 55,
      spAtk: 45,
      spDef: 70,
      speed: 45,
    },
  },
  {
    number: 87,
    name: "Dewgong",
    type: ["Água", "Gelo"],
    description:
      "Todo o seu corpo é branco como a neve. Incólume até mesmo pelo frio intenso, ele nada poderosamente em águas geladas.",
    height: 1.7,
    weight: 120.0,
    Gender: ["feminino", "masculino"],
    category: "Leão Marinho",
    Abilities: [
      "Thick Fat / Gordura Espessa",
      "Hydration / Hidratação",
      "Ice Body / Corpo de Gelo",
    ],
    baseStats: {
      hp: 90,
      attack: 70,
      defense: 80,
      spAtk: 70,
      spDef: 95,
      speed: 70,
    },
  },
  {
    number: 88,
    name: "Grimer",
    type: ["Veneno"],
    description:
      "Nascidos do lodo, esses Pokémon agora se reúnem em locais poluídos e aumentam as bactérias em seus corpos.",
    height: 0.9,
    weight: 30.0,
    Gender: ["feminino", "masculino"],
    category: "Lama",
    Abilities: [
      "Stench / Fedor",
      "Sticky Hold / Firme",
      "Poison Touch / Toque Tóxico",
    ],
    baseStats: {
      hp: 80,
      attack: 80,
      defense: 50,
      spAtk: 40,
      spDef: 50,
      speed: 25,
    },
  },
  {
    number: 89,
    name: "Muk",
    type: ["Veneno"],
    description:
      "Está densamente coberto com uma lama imunda e vil. É tão tóxico que até suas pegadas contêm veneno.",
    height: 1.2,
    weight: 30.0,
    Gender: ["feminino", "masculino"],
    category: "Lama",
    Abilities: [
      "Stench / Fedor",
      "Sticky Hold / Firme",
      "Poison Touch / Toque Tóxico",
    ],
    baseStats: {
      hp: 105,
      attack: 105,
      defense: 75,
      spAtk: 65,
      spDef: 100,
      speed: 50,
    },
  },
  {
    number: 90,
    name: "Shellder",
    type: ["Água"],
    description:
      "É envolto em uma casca que é mais dura que o diamante. Por dentro, no entanto, é surpreendentemente macio.",
    height: 0.3,
    weight: 4.0,
    Gender: ["feminino", "masculino"],
    category: "Bivalve",
    Abilities: [
      "Shell Armor / Armadura de Concha",
      "Skill Link / Ligação de Habilidade",
      "Overcoat / Manto",
    ],
    baseStats: {
      hp: 30,
      attack: 65,
      defense: 100,
      spAtk: 45,
      spDef: 25,
      speed: 40,
    },
  },
  {
    number: 91,
    name: "Cloyster",
    type: ["Água", "Gelo"],
    description:
      "Cloyster que vivem em mares com fortes correntes de maré crescem grandes e pontiagudos em suas conchas.",
    height: 1.5,
    weight: 132.5,
    Gender: ["feminino", "masculino"],
    category: "Molusco",
    Abilities: [
      "Shell Armor / Armadura de Concha",
      "Skill Link / Ligação de Habilidade",
      "Overcoat / Manto",
    ],
    baseStats: {
      hp: 50,
      attack: 95,
      defense: 180,
      spAtk: 85,
      spDef: 45,
      speed: 70,
    },
  },
  {
    number: 92,
    name: "Gastly",
    type: ["Fantasma", "Veneno"],
    description:
      "Ele envolve seu oponente em seu corpo gasoso, enfraquecendo lentamente sua presa ao envenená-la através da pele.",
    height: 1.3,
    weight: 0.1,
    Gender: ["sem gênero"],
    category: "Gás",
    Abilities: ["Levitate / Levitação"],
    baseStats: {
      hp: 30,
      attack: 35,
      defense: 30,
      spAtk: 100,
      spDef: 35,
      speed: 80,
    },
  },
  {
    number: 93,
    name: "Haunter",
    type: ["Fantasma", "Veneno"],
    description:
      "Ele gosta de se esconder no escuro e bater nos ombros com uma mão gasosa. Seu toque causa estremecimento sem fim.",
    height: 1.6,
    weight: 0.1,
    Gender: ["sem gênero"],
    category: "Gás",
    Abilities: ["Levitate / Levitação"],
    baseStats: {
      hp: 45,
      attack: 50,
      defense: 45,
      spAtk: 115,
      spDef: 55,
      speed: 95,
    },
  },
  {
    number: 94,
    name: "Gengar",
    type: ["Fantasma", "Veneno"],
    description:
      "Para roubar a vida de seu alvo, ele se esconde na sombra da presa e silenciosamente espera por uma oportunidade.",
    height: 1.5,
    weight: 40.5,
    Gender: ["feminino", "masculino"],
    category: "Sombra",
    Abilities: ["Cursed Body / Corpo Amaldiçoado"],
    baseStats: {
      hp: 60,
      attack: 65,
      defense: 60,
      spAtk: 130,
      spDef: 75,
      speed: 110,
    },
  },
  {
    number: 95,
    name: "Onix",
    type: ["Pedra", "Terra"],
    description:
      "À medida que escava o solo, absorve muitos objetos duros. É isso que torna seu corpo tão sólido.",
    height: 8.8,
    weight: 210.0,
    Gender: ["feminino", "masculino"],
    category: "Serpente",
    Abilities: [
      "Rock Head / Cabeça de Pedra",
      "Sturdy / Firme",
      "Weak Armor / Armadura Fraca",
    ],
    baseStats: {
      hp: 35,
      attack: 45,
      defense: 160,
      spAtk: 30,
      spDef: 45,
      speed: 70,
    },
  },
  {
    number: 96,
    name: "Drowzee",
    type: ["Psíquico"],
    description:
      "Ele se lembra de cada sonho que come. Raramente come os sonhos dos adultos porque os das crianças são muito mais saborosos.",
    height: 1.0,
    weight: 32.4,
    Gender: ["feminino", "masculino"],
    category: "Hipnose",
    Abilities: [
      "Insomnia / Insônia",
      "Forewarn / Antecipação",
      "Inner Focus / Foco Interno",
    ],
    baseStats: {
      hp: 60,
      attack: 48,
      defense: 45,
      spAtk: 43,
      spDef: 90,
      speed: 42,
    },
  },
  {
    number: 97,
    name: "Hypno",
    type: ["Psíquico"],
    description:
      "Quando ele trava os olhos com um inimigo, ele usa uma mistura de movimentos psíquicos, como Hipnose e Confusão.",
    height: 1.6,
    weight: 75.6,
    Gender: ["feminino", "masculino"],
    category: "Hipnose",
    Abilities: [
      "Insomnia / Insônia",
      "Forewarn / Antecipação",
      "Inner Focus / Foco Interno",
    ],
    baseStats: {
      hp: 85,
      attack: 73,
      defense: 70,
      spAtk: 73,
      spDef: 115,
      speed: 67,
    },
  },
  {
    number: 98,
    name: "Krabby",
    type: ["Água"],
    description:
      "Pode ser encontrado perto do mar. As pinças grandes voltam a crescer se forem arrancadas de seus encaixes.",
    height: 0.4,
    weight: 6.5,
    Gender: ["feminino", "masculino"],
    category: "Caranguejo",
    Abilities: [
      "Hyper Cutter / Hiper Cortador",
      "Shell Armor / Armadura de Concha",
      "Sheer Force / Força Bruta",
    ],
    baseStats: {
      hp: 30,
      attack: 105,
      defense: 90,
      spAtk: 25,
      spDef: 25,
      speed: 50,
    },
  },
  {
    number: 99,
    name: "Kingler",
    type: ["Água"],
    description:
      "A pinça maior tem força de 10.000 cavalos de potência. No entanto, é tão pesado que é difícil apontar.",
    height: 1.3,
    weight: 60.0,
    Gender: ["feminino", "masculino"],
    category: "Caranguejo",
    Abilities: [
      "Hyper Cutter / Hiper Cortador",
      "Shell Armor / Armadura de Concha",
      "Sheer Force / Força Bruta",
    ],
    baseStats: {
      hp: 55,
      attack: 130,
      defense: 115,
      spAtk: 50,
      spDef: 50,
      speed: 75,
    },
  },
  {
    number: 100,
    name: "Voltorb",
    type: ["Elétrico"],
    description:
      "Ele rola para se mover. Se o solo for irregular, um solavanco repentino ao bater em uma saliência pode fazer com que ele exploda.",
    height: 0.5,
    weight: 10.4,
    Gender: ["sem gênero"],
    category: "Bola",
    Abilities: [
      "Soundproof / À Prova de Som",
      "Static / Estática",
      "Aftermath / Consequência",
    ],
    baseStats: {
      hp: 40,
      attack: 30,
      defense: 50,
      spAtk: 55,
      spDef: 55,
      speed: 100,
    },
  },
  {
    number: 101,
    name: "Electrode",
    type: ["Elétrico"],
    description:
      "Quanto mais energia ele carrega, mais rápido ele fica. Mas isso também torna mais provável que exploda.",
    height: 1.2,
    weight: 66.6,
    Gender: ["sem gênero"],
    category: "Bola",
    Abilities: [
      "Soundproof / À Prova de Som",
      "Static / Estática",
      "Aftermath / Consequência",
    ],
    baseStats: {
      hp: 60,
      attack: 50,
      defense: 70,
      spAtk: 80,
      spDef: 80,
      speed: 150,
    },
  },
  {
    number: 102,
    name: "Exeggcute",
    type: ["Grama", "Psíquico"],
    description:
      "Embora possa parecer apenas um monte de ovos, é um Pokémon adequado. Exeggcute se comunica com outros de sua espécie via telepatia, aparentemente.",
    height: 0.4,
    weight: 2.5,
    Gender: ["sem gênero"],
    category: "Ovo Palmeira",
    Abilities: [
      "Chlorophyll / Clorofila",
      "Harvest / Colheita",
      "Frisk / Farejar",
    ],
    baseStats: {
      hp: 60,
      attack: 40,
      defense: 80,
      spAtk: 60,
      spDef: 45,
      speed: 40,
    },
  },
  {
    number: 103,
    name: "Exeggutor",
    type: ["Grama", "Psíquico"],
    description:
      "Cada uma das três cabeças de Exeggutor está pensando em pensamentos diferentes. Os três não parecem estar muito interessados um no outro.",
    height: 2.0,
    weight: 120.0,
    Gender: ["feminino", "masculino"],
    category: "Coco",
    Abilities: [
      "Chlorophyll / Clorofila",
      "Harvest / Colheita",
      "Frisk / Farejar",
    ],
    baseStats: {
      hp: 95,
      attack: 95,
      defense: 85,
      spAtk: 125,
      spDef: 65,
      speed: 55,
    },
  },
  {
    number: 104,
    name: "Cubone",
    type: ["Terra"],
    description:
      "Quando a memória de sua falecida mãe o leva às lágrimas, seus gritos ecoam tristemente dentro do crânio que ele usa em sua cabeça.",
    height: 0.4,
    weight: 6.5,
    Gender: ["feminino", "masculino"],
    category: "Solitário",
    Abilities: [
      "Rock Head / Cabeça de Pedra",
      "Lightning Rod / Pára-raios",
      "Battle Armor / Armadura de Batalha",
    ],
    baseStats: {
      hp: 50,
      attack: 50,
      defense: 95,
      spAtk: 40,
      spDef: 50,
      speed: 35,
    },
  },
  {
    number: 105,
    name: "Marowak",
    type: ["Terra"],
    description:
      "Este Pokémon superou sua tristeza para desenvolver um novo corpo robusto. Marowak enfrenta seus oponentes bravamente, usando um osso como arma.",
    height: 1.0,
    weight: 45.0,
    Gender: ["feminino", "masculino"],
    category: "Osso",
    Abilities: [
      "Rock Head / Cabeça de Pedra",
      "Lightning Rod / Pára-raios",
      "Battle Armor / Armadura de Batalha",
    ],
    baseStats: {
      hp: 60,
      attack: 80,
      defense: 110,
      spAtk: 50,
      spDef: 80,
      speed: 45,
    },
  },
  {
    number: 106,
    name: "Hitmonlee",
    type: ["Lutador"],
    description:
      "Este incrível Pokémon tem um incrível senso de equilíbrio. Pode chutar sucessivamente de qualquer posição.",
    height: 1.5,
    weight: 49.8,
    Gender: ["sem gênero"],
    category: "Chute",
    Abilities: [
      "Limber / Esquivar-se",
      "Reckless / Audácia",
      "Unburden / Leveza",
    ],
    baseStats: {
      hp: 50,
      attack: 120,
      defense: 53,
      spAtk: 35,
      spDef: 110,
      speed: 87,
    },
  },
  {
    number: 107,
    name: "Hitmonchan",
    type: ["Lutador"],
    description:
      "Seus socos cortam o ar. Eles são lançados a uma velocidade tão alta que até mesmo um leve arranhão pode causar uma queimadura.",
    height: 1.4,
    weight: 50.2,
    Gender: ["sem gênero"],
    category: "Soco",
    Abilities: [
      "Keen Eye / Olho Vivo",
      "Iron Fist / Punho de Ferro",
      "Inner Focus / Foco Interno",
    ],
    baseStats: {
      hp: 50,
      attack: 105,
      defense: 79,
      spAtk: 35,
      spDef: 110,
      speed: 76,
    },
  },
  {
    number: 108,
    name: "Lickitung",
    type: ["Normal"],
    description:
      "Se a saliva pegajosa deste Pokémon cair em você e você não a limpar, uma coceira intensa se instalará. A coceira também não vai embora.",
    height: 1.2,
    weight: 65.5,
    Gender: ["feminino", "masculino"],
    category: "Lamber",
    Abilities: [
      "Own Tempo / Ritmo Próprio",
      "Oblivious / Desatento",
      "Cloud Nine / Sem Preocupações",
    ],
    baseStats: {
      hp: 90,
      attack: 55,
      defense: 75,
      spAtk: 60,
      spDef: 75,
      speed: 30,
    },
  },
  {
    number: 109,
    name: "Koffing",
    type: ["Veneno"],
    description:
      "Seu corpo está cheio de gás venenoso. Ele flutua em depósitos de lixo, procurando a fumaça do lixo cru e apodrecido.",
    height: 0.6,
    weight: 1.0,
    Gender: ["sem gênero"],
    category: "Gás Venenoso",
    Abilities: ["Levitate / Levitação"],
    baseStats: {
      hp: 40,
      attack: 65,
      defense: 95,
      spAtk: 60,
      spDef: 45,
      speed: 35,
    },
  },
  {
    number: 110,
    name: "Weezing",
    type: ["Veneno"],
    description:
      "Cresce alimentando-se dos gases liberados pelo lixo. Embora muito raros, trigêmeos foram encontrados.",
    height: 1.2,
    weight: 9.5,
    Gender: ["sem gênero"],
    category: "Gás Venenoso",
    Abilities: ["Levitate / Levitação"],
    baseStats: {
      hp: 65,
      attack: 90,
      defense: 120,
      spAtk: 85,
      spDef: 70,
      speed: 60,
    },
  },
  {
    number: 111,
    name: "Rhyhorn",
    type: ["Terra", "Pedra"],
    description:
      "Forte, mas não muito brilhante, este Pokémon pode destruir até mesmo um arranha-céu com seus equipamentos de carregamento.",
    height: 1.0,
    weight: 115.0,
    Gender: ["feminino", "masculino"],
    category: "Espigão",
    Abilities: [
      "Lightning Rod / Pára-raios",
      "Rock Head / Cabeça de Pedra",
      "Reckless / Audácia",
    ],
    baseStats: {
      hp: 80,
      attack: 85,
      defense: 95,
      spAtk: 30,
      spDef: 30,
      speed: 25,
    },
  },
  {
    number: 112,
    name: "Rhydon",
    type: ["Terra", "Pedra"],
    description:
      "Ele começa a andar sobre as patas traseiras após a evolução. Ele pode perfurar pedras com seu chifre.",
    height: 1.9,
    weight: 120.0,
    Gender: ["feminino", "masculino"],
    category: "Furioso",
    Abilities: [
      "Lightning Rod / Pára-raios",
      "Rock Head / Cabeça de Pedra",
      "Reckless / Audácia",
    ],
    baseStats: {
      hp: 105,
      attack: 130,
      defense: 120,
      spAtk: 45,
      spDef: 45,
      speed: 40,
    },
  },
  {
    number: 113,
    name: "Chansey",
    type: ["Normal"],
    description:
      "Este gentil Pokémon põe ovos altamente nutritivos e os compartilha com Pokémon ou pessoas feridas.",
    height: 1.1,
    weight: 34.6,
    Gender: ["feminino", "masculino"],
    category: "Ovo",
    Abilities: [
      "Natural Cure / Cura Natural",
      "Serene Grace / Graça Serena",
      "Healer / Cura",
    ],
    baseStats: {
      hp: 250,
      attack: 5,
      defense: 5,
      spAtk: 35,
      spDef: 105,
      speed: 50,
    },
  },
  {
    number: 114,
    name: "Tangela",
    type: ["Grama"],
    description:
      "Escondido sob um emaranhado de vinhas que cresce sem parar, mesmo que as vinhas sejam arrancadas, a verdadeira aparência deste Pokémon permanece um mistério.",
    height: 1.0,
    weight: 35.0,
    Gender: ["feminino", "masculino"],
    category: "Vinha",
    Abilities: [
      "Chlorophyll / Clorofila",
      "Leaf Guard / Folha Guarda",
      "Regenerator / Regenerador",
    ],
    baseStats: {
      hp: 65,
      attack: 55,
      defense: 115,
      spAtk: 100,
      spDef: 40,
      speed: 60,
    },
  },
  {
    number: 115,
    name: "Kangaskhan",
    type: ["Normal"],
    description:
      "Embora esteja carregando seu bebê em uma bolsa em sua barriga, Kangaskhan é rápido em seus pés. Ele intimida seus oponentes com golpes rápidos.",
    height: 2.2,
    weight: 80.0,
    Gender: ["feminino", "masculino"],
    category: "Parental",
    Abilities: [
      "Early Bird / Passarinho Madrugador",
      "Scrappy / Inflexível",
      "Inner Focus / Foco Interno",
    ],
    baseStats: {
      hp: 105,
      attack: 95,
      defense: 80,
      spAtk: 40,
      spDef: 80,
      speed: 90,
    },
  },
  {
    number: 116,
    name: "Horsea",
    type: ["Água"],
    description:
      "Horsea faz sua casa em oceanos com correntes suaves. Se este Pokémon estiver sob ataque, ele cospe tinta preta e foge.",
    height: 0.4,
    weight: 8.0,
    Gender: ["feminino", "masculino"],
    category: "Dragão",
    Abilities: [
      "Swift Swim / Nado Rápido",
      "Sniper / Atirador",
      "Damp / Umidade",
    ],
    baseStats: {
      hp: 30,
      attack: 40,
      defense: 70,
      spAtk: 70,
      spDef: 25,
      speed: 60,
    },
  },
  {
    number: 117,
    name: "Seadra",
    type: ["Água"],
    description:
      "São os machos que criam os filhotes. Enquanto Seadra cria filhotes, os espinhos em suas costas secretam um veneno mais espesso e forte.",
    height: 1.2,
    weight: 25.0,
    Gender: ["feminino", "masculino"],
    category: "Dragão",
    Abilities: [
      "Poison Point / Ponto Venenoso",
      "Sniper / Atirador",
      "Damp / Umidade",
    ],
    baseStats: {
      hp: 55,
      attack: 65,
      defense: 95,
      spAtk: 95,
      spDef: 45,
      speed: 85,
    },
  },
  {
    number: 118,
    name: "Goldeen",
    type: ["Água"],
    description:
      "Suas barbatanas dorsal, peitoral e caudal ondulam elegantemente na água. É por isso que é conhecido como o Dançarino da Água.",
    height: 0.6,
    weight: 15.0,
    Gender: ["feminino", "masculino"],
    category: "Peixe",
    Abilities: [
      "Swift Swim / Nado Rápido",
      "Water Veil / Véu de Água",
      "Lightning Rod / Pára-raios",
    ],
    baseStats: {
      hp: 45,
      attack: 67,
      defense: 60,
      spAtk: 35,
      spDef: 50,
      speed: 63,
    },
  },
  {
    number: 119,
    name: "Seaking",
    type: ["Água"],
    description:
      "No outono, seu corpo fica mais gorduroso ao se preparar para pedir um companheiro em casamento. Ele assume lindas cores.",
    height: 1.3,
    weight: 39.0,
    Gender: ["feminino", "masculino"],
    category: "Peixe",
    Abilities: [
      "Swift Swim / Nado Rápido",
      "Water Veil / Véu de Água",
      "Lightning Rod / Pára-raios",
    ],
    baseStats: {
      hp: 80,
      attack: 92,
      defense: 65,
      spAtk: 65,
      spDef: 80,
      speed: 68,
    },
  },
  {
    number: 120,
    name: "Staryu",
    type: ["Água"],
    description:
      "Se você visitar uma praia no final do verão, poderá ver grupos de Staryu se iluminando em um ritmo constante.",
    height: 0.8,
    weight: 34.5,
    Gender: ["sem gênero"],
    category: "Estrela",
    Abilities: [
      "Illuminate / Iluminação",
      "Natural Cure / Cura Natural",
      "Analytic / Analítico",
    ],
    baseStats: {
      hp: 30,
      attack: 45,
      defense: 55,
      spAtk: 70,
      spDef: 55,
      speed: 85,
    },
  },
  {
    number: 121,
    name: "Starmie",
    type: ["Água", "Psíquico"],
    description:
      "Este Pokémon possui um órgão conhecido como núcleo. O órgão brilha em sete cores quando Starmie está liberando seus potentes poderes psíquicos.",
    height: 1.1,
    weight: 80.0,
    Gender: ["sem gênero"],
    category: "Misterioso",
    Abilities: [
      "Illuminate / Iluminação",
      "Natural Cure / Cura Natural",
      "Analytic / Analítico",
    ],
    baseStats: {
      hp: 60,
      attack: 75,
      defense: 85,
      spAtk: 100,
      spDef: 85,
      speed: 115,
    },
  },
  {
    number: 122,
    name: "Mr. Mime",
    type: ["Psíquico", "Fada"],
    description:
      "É um especialista em pantomima que pode criar paredes invisíveis, mas sólidas, usando gestos de mímica.",
    height: 1.3,
    weight: 54.5,
    Gender: ["feminino", "masculino"],
    category: "Barreira",
    Abilities: [
      "Soundproof / À Prova de Som",
      "Filter / Filtro",
      "Technician / Técnico",
    ],
    baseStats: {
      hp: 40,
      attack: 45,
      defense: 65,
      spAtk: 100,
      spDef: 120,
      speed: 90,
    },
  },
  {
    number: 123,
    name: "Scyther",
    type: ["Inseto", "Voador"],
    description:
      "Ele corta a grama com suas foices afiadas, movendo-se rápido demais para ser rastreado pelo olho humano.",
    height: 1.5,
    weight: 56.0,
    Gender: ["feminino", "masculino"],
    category: "Mantis",
    Abilities: [
      "Swarm / Enxame",
      "Technician / Técnico",
      "Steadfast / Inabalável",
    ],
    baseStats: {
      hp: 70,
      attack: 110,
      defense: 80,
      spAtk: 55,
      spDef: 80,
      speed: 105,
    },
  },
  {
    number: 124,
    name: "Jynx",
    type: ["Gelo", "Psíquico"],
    description:
      "Em certas partes de Galar, Jynx já foi temida e adorada como a Rainha do Gelo.",
    height: 1.4,
    weight: 40.6,
    Gender: ["feminino", "masculino"],
    category: "Beijo",
    Abilities: [
      "Oblivious / Desatento",
      "Forewarn / Antecipação",
      "Dry Skin / Pele Seca",
    ],
    baseStats: {
      hp: 65,
      attack: 50,
      defense: 35,
      spAtk: 115,
      spDef: 95,
      speed: 95,
    },
  },
  {
    number: 125,
    name: "Electabuzz",
    type: ["Elétrico"],
    description:
      "Muitas usinas de energia mantêm Pokémon do tipo Ground por perto como uma defesa contra Electabuzz que vem em busca de eletricidade.",
    height: 1.1,
    weight: 30.0,
    Gender: ["feminino", "masculino"],
    category: "Elétrico",
    Abilities: [
      "Static / Estática",
      "Vital Spirit / Espírito Vital",
      "Pressure / Pressão",
    ],
    baseStats: {
      hp: 65,
      attack: 83,
      defense: 57,
      spAtk: 95,
      spDef: 85,
      speed: 105,
    },
  },
  {
    number: 126,
    name: "Magmar",
    type: ["Fogo"],
    description:
      "Magmar despacha sua presa com fogo. Mas ele se arrepende desse hábito quando percebe que queimou sua presa pretendida em uma batata frita carbonizada.",
    height: 1.3,
    weight: 44.5,
    Gender: ["feminino", "masculino"],
    category: "Escapar",
    Abilities: [
      "Flame Body / Corpo Flamejante",
      "Vital Spirit / Espírito Vital",
      "Anger Point / Fúria",
    ],
    baseStats: {
      hp: 65,
      attack: 95,
      defense: 57,
      spAtk: 100,
      spDef: 85,
      speed: 93,
    },
  },

  {
    number: 127,
    name: "Pinsir",
    type: ["Inseto"],
    description:
      "Esses Pokémon julgam uns aos outros com base em pinças. Pinças mais grossas e impressionantes criam mais popularidade com o sexo oposto.",
    height: 1.5,
    weight: 55.0,
    Gender: ["feminino", "masculino"],
    category: "Besouro",
    Abilities: [
      "Hyper Cutter / Hiper Cortador",
      "Mold Breaker / Ruptura de Moldes",
      "Moxie / Autoestima",
    ],
    baseStats: {
      hp: 65,
      attack: 125,
      defense: 100,
      spAtk: 55,
      spDef: 70,
      speed: 85,
    },
  },
  {
    number: 128,
    name: "Tauros",
    type: ["Normal"],
    description:
      "Uma vez que aponta para sua presa, ele faz uma carga de cabeça. É famoso por sua natureza violenta.",
    height: 1.4,
    weight: 88.4,
    Gender: ["feminino", "masculino"],
    category: "Touro",
    Abilities: [
      "Intimidate / Intimidar",
      "Anger Point / Fúria",
      "Sheer Force / Força Bruta",
    ],
    baseStats: {
      hp: 75,
      attack: 100,
      defense: 95,
      spAtk: 40,
      spDef: 70,
      speed: 110,
    },
  },
  {
    number: 129,
    name: "Magikarp",
    type: ["Água"],
    description:
      "Um Pokémon patético e pouco poderoso. Pode saltar alto em raras ocasiões, mas nunca mais de dois metros.",
    height: 0.9,
    weight: 10.0,
    Gender: ["feminino", "masculino"],
    category: "Peixe",
    Abilities: [
      "Swift Swim / Nado Rápido",
      "Rattled / Assustado",
      "Moxie / Autoestima",
    ],
    baseStats: {
      hp: 20,
      attack: 10,
      defense: 55,
      spAtk: 15,
      spDef: 20,
      speed: 80,
    },
  },

  {
    number: 130,
    name: "Gyarados",
    type: ["Água", "Voador"],
    description:
      "Uma vez que aparece, ele entra em fúria. Ele permanece enfurecido até destruir tudo ao seu redor.",
    height: 6.5,
    weight: 235.0,
    Gender: ["feminino", "masculino"],
    category: "Atrocidade",
    Abilities: ["Intimidate / Intimidar", "Moxie / Autoestima"],
    baseStats: {
      hp: 95,
      attack: 125,
      defense: 79,
      spAtk: 60,
      spDef: 100,
      speed: 81,
    },
  },
  {
    number: 131,
    name: "Lapras",
    type: ["Água", "Gelo"],
    description:
      "Adora cruzar o mar com pessoas e Pokémon nas costas. Ele entende a fala humana.",
    height: 2.5,
    weight: 220.0,
    Gender: ["feminino", "masculino"],
    category: "Transporte",
    Abilities: [
      "Water Absorb / Absorção de Água",
      "Shell Armor / Armadura de Concha",
      "Hydration / Hidratação",
    ],
    baseStats: {
      hp: 130,
      attack: 85,
      defense: 80,
      spAtk: 85,
      spDef: 95,
      speed: 60,
    },
  },

  {
    number: 132,
    name: "Ditto",
    type: ["Normal"],
    description:
      "Sua capacidade de transformação é perfeita. No entanto, se for feito para rir, não consegue manter seu disfarce.",
    height: 0.3,
    weight: 4.0,
    Gender: ["sem gênero"],
    category: "Transformação",
    Abilities: ["Limber / Esquivar-se", "Imposter / Impostor"],
    baseStats: {
      hp: 48,
      attack: 48,
      defense: 48,
      spAtk: 48,
      spDef: 48,
      speed: 48,
    },
  },

  {
    number: 133,
    name: "Eevee",
    type: ["Normal"],
    description:
      "Sua capacidade de evoluir em muitas formas permite que ela se adapte suave e perfeitamente a qualquer ambiente.",
    height: 0.3,
    weight: 6.5,
    Gender: ["feminino", "masculino"],
    category: "Evolução",
    Abilities: [
      "Run Away / Fugir",
      "Adaptability / Adaptabilidade",
      "Anticipation / Antecipação",
    ],
    baseStats: {
      hp: 55,
      attack: 55,
      defense: 50,
      spAtk: 45,
      spDef: 65,
      speed: 55,
    },
  },
  {
    number: 134,
    name: "Vaporeon",
    type: ["Água"],
    description: "Vive perto da água. Sua longa cauda é marcada por uma barbatana, que muitas vezes é confundida com a de uma sereia.",
    height: 1.0,
    weight: 29.0,
    Gender: ["feminino", "masculino"],
    category: "Bolha",
    Abilities: ["Water Absorb / Absorção de Água", "Hydration / Hidratação"],
    baseStats: {
        hp: 130,
        attack: 65,
        defense: 60,
        spAtk: 110,
        spDef: 95,
        speed: 65,
    }
},
{
  number: 135,
  name: "Jolteon",
  type: ["Elétrico"],
  description: "Ele concentra as fracas cargas elétricas emitidas por suas células e lança raios perversos.",
  height: 0.8,
  weight: 24.5,
  Gender: ["feminino", "masculino"],
  category: "Relâmpago",
  Abilities: ["Volt Absorb / Absorção de Voltagem", "Quick Feet / Pés Ligeiros"],
  baseStats: {
      hp: 65,
      attack: 65,
      defense: 60,
      spAtk: 110,
      spDef: 95,
      speed: 130,
  }
},
{
  number: 136,
  name: "Flareon",
  type: ["Fogo"],
  description: "O ar inalado é levado ao seu saco de chamas, aquecido e exalado como fogo que atinge mais de 3.000 graus Fahrenheit.",
  height: 0.9,
  weight: 25.0,
  Gender: ["feminino", "masculino"],
  category: "Chama",
  Abilities: ["Flash Fire / Absorve-Fogo", "Guts / Marra", "Guts / Marra"],
  baseStats: {
      hp: 65,
      attack: 130,
      defense: 60,
      spAtk: 95,
      spDef: 110,
      speed: 65,
  }
},
{
  number: 137,
  name: "Porygon",
  type: ["Normal"],
  description: "Tecnologia de ponta foi usada para criar Porygon. Foi o primeiro Pokémon artificial a ser criado por meio de programação de computador.",
  height: 0.8,
  weight: 36.5,
  Gender: ["sem gênero"],
  category: "Virtual",
  Abilities: ["Trace / Traço", "Download / Download", "Analytic / Analítico"],
  baseStats: {
      hp: 65,
      attack: 60,
      defense: 70,
      spAtk: 85,
      spDef: 75,
      speed: 40,
  }
},
{
  number: 138,
  name: "Omanyte",
  type: ["Pedra", "Água"],
  description: "Como alguns Omanyte conseguem escapar após serem restaurados ou são soltos na natureza por pessoas, essa espécie está se tornando um problema.",
  height: 0.4,
  weight: 7.5,
  Gender: ["feminino", "masculino"],
  category: "Espiral",
  Abilities: ["Swift Swim / Nado Rápido", "Shell Armor / Armadura de Concha", "Weak Armor / Armadura Frágil"],
  baseStats: {
      hp: 35,
      attack: 40,
      defense: 100,
      spAtk: 90,
      spDef: 55,
      speed: 35,
  }
},
{
  number: 139,
  name: "Omastar",
  type: ["Pedra", "Água"],
  description: "Pesado por uma concha grande e pesada, Omastar não conseguia se mover muito rápido. Alguns dizem que foi extinto porque não conseguia pegar comida.",
  height: 1.0,
  weight: 35.0,
  Gender: ["feminino", "masculino"],
  category: "Espiral",
  Abilities: ["Swift Swim / Nado Rápido", "Shell Armor / Armadura de Concha", "Weak Armor / Armadura Frágil"],
  baseStats: {
      hp: 70,
      attack: 60,
      defense: 125,
      spAtk: 115,
      spDef: 70,
      speed: 55,
  }
},
{
  number: 140,
  name: "Kabuto",
  type: ["Pedra", "Água"],
  description: "Esta espécie está quase totalmente extinta. Kabuto muda a cada três dias, tornando suas cascas cada vez mais duras.",
  height: 0.5,
  weight: 11.5,
  Gender: ["feminino", "masculino"],
  category: "Concha",
  Abilities: ["Swift Swim / Nado Rápido", "Battle Armor / Armadura de Batalha", "Weak Armor / Armadura Frágil"],
  baseStats: {
      hp: 30,
      attack: 80,
      defense: 90,
      spAtk: 55,
      spDef: 45,
      speed: 55,
  }
},
{
  number: 141,
  name: "Kabutops",
  type: ["Pedra", "Água"],
  description: "Kabutops corta sua presa e suga os fluidos. As partes do corpo descartadas se tornam comida para outros Pokémon.",
  height: 1.3,
  weight: 40.5,
  Gender: ["feminino", "masculino"],
  category: "Concha",
  Abilities: ["Swift Swim / Nado Rápido", "Battle Armor / Armadura de Batalha", "Weak Armor / Armadura Frágil"],
  baseStats: {
      hp: 60,
      attack: 115,
      defense: 105,
      spAtk: 65,
      spDef: 70,
      speed: 80,
  }
},
{
  number: 142,
  name: "Aerodactyl",
  type: ["Pedra", "Voador"],
  description: "Este é um Pokémon feroz dos tempos antigos. Aparentemente, mesmo a tecnologia moderna é incapaz de produzir um espécime perfeitamente restaurado.",
  height: 1.8,
  weight: 59.0,
  Gender: ["feminino", "masculino"],
  category: "Fóssil",
  Abilities: ["Rock Head / Cabeça de Pedra", "Pressure / Pressão", "Unnerve / Impertinência"],
  baseStats: {
      hp: 80,
      attack: 105,
      defense: 65,
      spAtk: 60,
      spDef: 75,
      speed: 130,
  }
},
{
  number: 143,
  name: "Snorlax",
  type: ["Normal"],
  description: "Seu estômago pode digerir qualquer tipo de alimento, mesmo que esteja mofado ou podre.",
  height: 2.1,
  weight: 460.0,
  Gender: ["feminino", "masculino"],
  category: "Dorminhoco",
  Abilities: ["Immunity / Imunidade", "Thick Fat / Gordura Espessa", "Gluttony / Gula"],
  baseStats: {
      hp: 160,
      attack: 110,
      defense: 65,
      spAtk: 65,
      spDef: 110,
      speed: 30,
  }
},
{
  number: 144,
  name: "Articuno",
  type: ["Gelo", "Voador"],
  description: "Este Pokémon pássaro lendário pode criar nevascas ao congelar a umidade do ar.",
  height: 1.7,
  weight: 55.4,
  Gender: ["sem gênero"],
  category: "Congelamento",
  Abilities: ["Pressure / Pressão", "Snow Cloak / Manto de Neve"],
  baseStats: {
      hp: 90,
      attack: 85,
      defense: 100,
      spAtk: 95,
      spDef: 125,
      speed: 85,
  }
},
{
  number: 145,
  name: "Zapdos",
  type: ["Elétrico", "Voador"],
  description: "Diz-se que este lendário Pokémon vive em nuvens de tempestade. Ele controla livremente relâmpagos.",
  height: 1.6,
  weight: 52.6,
  Gender: ["sem gênero"],
  category: "Elétrico",
  Abilities: ["Pressure / Pressão", "Static / Estática"],
  baseStats: {
      hp: 90,
      attack: 90,
      defense: 85,
      spAtk: 125,
      spDef: 90,
      speed: 100,
  }
},
{
  number: 146,
  name: "Moltres",
  type: ["Fogo", "Voador"],
  description: "É um dos lendários Pokémon pássaro. Dizem que sua aparência indica a chegada da primavera.",
  height: 2.0,
  weight: 60.0,
  Gender: ["sem gênero"],
  category: "Flamejante",
  Abilities: ["Pressure / Pressão", "Flame Body / Corpo Flamejante"],
  baseStats: {
      hp: 90,
      attack: 100,
      defense: 90,
      spAtk: 125,
      spDef: 85,
      speed: 90,
  }
},
{
  number: 147,
  name: "Dratini",
  type: ["Dragão"],
  description: "Ele lança muitas camadas de pele à medida que cresce. Durante este processo, é protegido por uma rápida cachoeira.",
  height: 1.8,
  weight: 3.3,
  Gender: ["feminino", "masculino"],
  category: "Dragão",
  Abilities: ["Shed Skin / Troca de Pele", "Marvel Scale / Pele de Dragão"],
  baseStats: {
      hp: 41,
      attack: 64,
      defense: 45,
      spAtk: 50,
      spDef: 50,
      speed: 50,
  }
},
{
  number: 148,
  name: "Dragonair",
  type: ["Dragão"],
  description: "Dizem que se emitir uma aura de todo o corpo, o clima começará a mudar instantaneamente.",
  height: 4.0,
  weight: 16.5,
  Gender: ["feminino", "masculino"],
  category: "Dragão",
  Abilities: ["Shed Skin / Troca de Pele", "Marvel Scale / Pele de Dragão"],
  baseStats: {
      hp: 61,
      attack: 84,
      defense: 65,
      spAtk: 70,
      spDef: 70,
      speed: 70,
  }
},
{
  number: 149,
  name: "Dragonite",
  type: ["Dragão", "Voador"],
  description: "Diz-se que algures no oceano existe uma ilha onde estes se reúnem. Só eles moram lá.",
  height: 2.2,
  weight: 210.0,
  Gender: ["feminino", "masculino"],
  category: "Dragão",
  Abilities: ["Inner Focus / Foco Interno", "Multiscale / Multiescala"],
  baseStats: {
      hp: 91,
      attack: 134,
      defense: 95,
      spAtk: 100,
      spDef: 100,
      speed: 80,
  }
},
{
  number: 150,
  name: "Mewtwo",
  type: ["Psíquico"],
  description: "Seu DNA é quase o mesmo de Mew. No entanto, seu tamanho e disposição são muito diferentes.",
  height: 2.0,
  weight: 122.0,
  Gender: ["sem gênero"],
  category: "Genético",
  Abilities: ["Pressure / Pressão", "Unnerve / Impertinência"],
  baseStats: {
      hp: 106,
      attack: 110,
      defense: 90,
      spAtk: 154,
      spDef: 90,
      speed: 130,
  }
},
{
  number: 151,
  name: "Mew",
  type: ["Psíquico"],
  description: "Quando visto através de um microscópio, o cabelo curto, fino e delicado deste Pokémon pode ser visto.",
  height: 0.4,
  weight: 4.0,
  Gender: ["sem gênero"],
  category: "Nova espécie",
  Abilities: ["Synchronize / Sincronia"],
  baseStats: {
      hp: 100,
      attack: 100,
      defense: 100,
      spAtk: 100,
      spDef: 100,
      speed: 100,
  }
}

];
